### ISSUE TITLE
How to resize toolbar content view height dynamically?

### ISSUE THREAD

**Issue by ghost** [zzxxx/JSQMessageCustomInputToolBar#1]
Hi,

My input toolbar content view has 2 rows . Top row for action buttons and bottom row for (input text view + send button)

I want to hide (input text + send button) view and show only action buttons. However, only when a "Chat" action button is clicked, do I need to show the bottom row

So, how can I resize the toolbar content view dynamically when hiding and un-hiding the bottom row?

Right now, inputToolbar.contentView.frame.height is a read-only property

**Comment by ghost** [comment]
@zzxxx 

Also, I've imported JSQMeesagesViewController as a pod into my project. 

I saw from the source code that *contentView  is a read-only property in JSQMessagesInputToolbar.h

So, is there a way to remove the read-only flag from the property of a pod without needing to copy the entire project?

**Comment by zzxxx** [comment]
@pardypanda Hello there :) 
[This must help](https://github.com/zzxxx/JSQMessageCustomInputToolBar/blob/master/JQSMessageCustomInputBar/YourAppName-Bridging-Header.h)

**Comment by pardypanda** [comment]
@zzxxx

**Comment by ghost** [comment]
@zzxxx Thanks for your response.

Can we chat about this over Skype (userid: tanayshah13)? 
I have a few more questions.

Using this solution, self.toolbarHeightConstraint always comes as nil

Thanks

**Comment by ghost** [comment]
Alright, I fixed it. 

I had copied the JSQMessagesViewController.xib from on older repo version which did not have the constraint in the XIB itself. 

After replacing the XIB with a more recent version which had the height constraint, problem got solved. 

I was able to change height of toolbar dynamically using:

            self.toolbarHeightConstraint.constant = 80.0
            self.inputToolbar.contentView.sizeToFit()
            self.inputToolbar.contentView.layoutIfNeeded()
            self.inputToolbar.layoutIfNeeded()

And using Stack Views inside the JSQMessagesInputToolbarContentView.xib, I am able to hide/show secondary row of action buttons

Thanks and lot for your help @zzxxx 

Appreciate it
